### ISSUE TITLE
ApiExample search doesn't work, throws exception

### ISSUE THREAD

**Issue by HAV0X1014** [c8ff/twitter-scraper-java#1]
First and foremost, thank you so much for your work! There aren't any working twitter scrapers for java, and this one so far seems quite good.

The exception thrown is below, and the code snippet is as well. This is the same code that is currently in the repo. Additional info, I am running this using Java 17 (Java 19 is default) and using gradle 8.5 instead of gradle 8.0

```
Exception in thread "main" java.lang.NullPointerException: Cannot read field "globalObjects" because "result" is null
	at dev.seeight.twitterscraper.impl.search.SearchResult.fromSearchAdaptiveResult(SearchResult.java:109)
	at dev.seeight.twitterscraper.config.ConfigSearch.resolve(ConfigSearch.java:79)
	at dev.seeight.twitterscraper.config.ConfigSearch.resolve(ConfigSearch.java:37)
	at dev.seeight.twitterscraper.TwitterApi.scrap(TwitterApi.java:121)
	at ApiExample.main(ApiExample.java:56)
```

```
// Similar as before, but this sends a search request.
SearchResult result = api.scrap(ConfigSearch.builder("(from:twitter) -filter:replies").count(4).build(), client);
// Print results
System.out.println(result);
// Save results.
Files.writeString(new File("search-result.json").toPath(), JsonUtil.toJson(result));
```

**Comment by c8ff** [comment]
Thank you! I can replicate this issue on my side. Although, there is another configuration that has the same result. Instead of `dev.seeight.twitterscraper.config.ConfigSearch` it's `dev.seeight.twitterscraper.config.timeline.ConfigSearchTimeline`. The updated code would be:

```java
var config = new ConfigSearchTimeline("(from:twitter) -filter:replies", null);
config.count = 4;
var result = api.scrap(config, client);
System.out.println(result);
```

The new class is a rewrite of the older one, and I forgot to remove/deprecate the old configuration and update the examples. 
Let me know if this works for you.

**Comment by HAV0X1014** [comment]
This code works great! I hope you're able to add a bit more documentation and commentary to this project, but aside from that thank you so much. I'll close this issue.
